#Oh shit script

$1=new-csedgedomainpattern -domain "AMCO.PL"
$2=new-csedgedomainpattern -domain "BR.FRUTAROM.COM"
$3=new-csedgedomainpattern -domain "BREMIL.COM.BR"
$4=new-csedgedomainpattern -domain "BSA.CA"
$5=new-csedgedomainpattern -domain "CH.FRUTAROM.COM"
$6=new-csedgedomainpattern -domain "CITRASOURCE.COM"
$7=new-csedgedomainpattern -domain "CZ.FRUTAROM.COM"
$8=new-csedgedomainpattern -domain "DE.FRUTAROM.COM"
$9=new-csedgedomainpattern -domain "ENZYMOTEC.COM"
$10=new-csedgedomainpattern -domain "ETOL.COM"
$11=new-csedgedomainpattern -domain "ETOL.SK"
$12=new-csedgedomainpattern -domain "ETOL.UA"
$13=new-csedgedomainpattern -domain "ETOL-JVE.CO.RS"
$14=new-csedgedomainpattern -domain "FLAVOURS.UK.COM"
$15=new-csedgedomainpattern -domain "FOODBLENDERS.CO.UK"
$16=new-csedgedomainpattern -domain "FR.FRUTAROM.COM"
$17=new-csedgedomainpattern -domain "FRUTAROM.PL"
$18=new-csedgedomainpattern -domain "FRUTAROMAP.COM"
$19=new-csedgedomainpattern -domain "FRUTAROMETOL.COM"
$20=new-csedgedomainpattern -domain "IBRWEB.COM"
$21=new-csedgedomainpattern -domain "INGRENAT.COM"
$22=new-csedgedomainpattern -domain "INVENTIVEFOOD.COM"
$23=new-csedgedomainpattern -domain "IRISHCOUNTRGOLD.CO.UK"
$24=new-csedgedomainpattern -domain "IRISHCOUNTRYGOLD.CO.UK"
$25=new-csedgedomainpattern -domain "MIGHTY.CO.TH"
$26=new-csedgedomainpattern -domain "NUTRAFUR.COM"
$27=new-csedgedomainpattern -domain "PIASA.COM"
$28=new-csedgedomainpattern -domain "PROTEIN.RU"
$29=new-csedgedomainpattern -domain "REDBROOK.IE"
$30=new-csedgedomainpattern -domain "RENE-AURENT.FR"
$31=new-csedgedomainpattern -domain "RENE-LAURENT.FR"
$32=new-csedgedomainpattern -domain "RO.FRUTAROM.COM"
$33=new-csedgedomainpattern -domain "RU.FRUTAROM.COM"
$34=new-csedgedomainpattern -domain "SI.FRUTAROM.COM"
$35=new-csedgedomainpattern -domain "SONAROME.COM"
$36=new-csedgedomainpattern -domain "TAURAURC.COM"
$37=new-csedgedomainpattern -domain "VAYAPHARMA.COM"
$38=new-csedgedomainpattern -domain "WFF.COM.VN"
$39=new-csedgedomainpattern -domain "WIBERG.EU"
$40=new-csedgedomainpattern -domain "ZA.FRUTAROM.COM"
$41=new-csedgedomainpattern -domain "bt.com"
$42=new-csedgedomainpattern -domain "btonecloud.com"
$43=new-csedgedomainpattern -domain "deutschepost.de"
$44=new-csedgedomainpattern -domain "dhl.com"
$45=new-csedgedomainpattern -domain "dpdhl.com"
$46=new-csedgedomainpattern -domain "exel.com"
$47=new-csedgedomainpattern -domain "frutarom.com"
$48=new-csedgedomainpattern -domain "frutarom.eu"
$49=new-csedgedomainpattern -domain "iff.com"
$50=new-csedgedomainpattern -domain "microsoft.com"
$51=new-csedgedomainpattern -domain "navisite.com"
$52=new-csedgedomainpattern -domain "pg.com"
$53=new-csedgedomainpattern -domain "powderpure.com"
$54=new-csedgedomainpattern -domain "unilever.com"
$55=New-CsEdgeDomainPattern -domain "noammeetings.lync.com"
$56=New-CsEdgeDomainPattern -domain "emeameetings.lync.com"
$57=New-CsEdgeDomainPattern -domain "apacmeetings.lync.com"
$58=New-CsEdgeDomainPattern -domain "resources.lync.com"
$newAllowList = New-CsEdgeAllowList -AllowedDomain $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55,$56,$57,$58
Set-CsTenantFederationConfiguration -AllowedDomains $newAllowList


Get-CsTenantFederationConfiguration | ft AllowedDomains -AutoSize -Wrap

